name: Build Doc

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun

      - name: Install dependencies
        run: bun install

      - name: Build with VitePress
        run: bun run docs:build
